site_name: Mina Rees Library Archives Processing Manual
theme:
  name: material
  favicon: img/favicon.ico
nav:
 - Home: README.md
 - About: about.md
 - DACS notes: notes.md
markdown_extensions:
  - toc:
      permalink: "#"