site_name: Mina Rees Library Archives Manual
site_url: https://gc-library.github.io/archive-docs/
theme:
  name: material
  favicon: img/favicon.ico
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.path
    - navigation.sections
    - navigation.indexes
    - navigation.tracking
    - toc.integrate
nav:
 - Home: README.md
 - About: about.md
 - DACS notes: notes.md
 - Scanning: 
   - scanning/index.md
   - Epson 13000XL: scanning/epson.md
 - JSTOR Institutional Collections: 
   - jstor/index.md
   - Student Newspapers Project: jstor/student-news.md
    
markdown_extensions:
  - toc:
      permalink: "#"
  - tables
  