site_name: Mina Rees Library Archives Manual
theme:
  name: material
  favicon: img/favicon.ico
  features:
    - navigation.path
    - navigation.indexes
    - navigation.top
nav:
 - Home: README.md
 - About: about.md
 - DACS notes: notes.md
 - Digitization: 
   - digitization/index.md
   - Documents: digitization/documents.md
   - Photos: digitization/photos.md
   - JSTOR Forum: 
     - forum/index.md
     - Student Newspapers Project: forum/student-news.md
    
markdown_extensions:
  - toc:
      permalink: "#"
  - tables
  