site_name: Mina Rees Library Archives Manual
theme:
  name: material
  favicon: img/favicon.ico
  features:
    - navigation.path
    - navigation.indexes
    - navigation.top
nav:
 - Home: README.md
 - About: about.md
 - DACS notes: notes.md
 - Digitization: digitization/index.md
     - JSTOR Forum: digitization/forum/index.md
     - Student Newspapers: digitization/forum/student-news.md
    
markdown_extensions:
  - toc:
      permalink: "#"
  - tables
  