site_name: Mina Rees Library Archives Manual
theme:
  name: material
  favicon: img/favicon.ico
  features:
    - navigation.path
    - navigation.top
nav:
 - Home: README.md
 - About: about.md
 - DACS notes: notes.md
 - Digitization: 
   - Introduction: digitization/intro.md
   - Epson 12000XL: digitization/epson.md
 - JSTOR Forum: 
   - Introduction: forum/intro.md
   - Student Newspapers Project: forum/student-news.md
    
markdown_extensions:
  - toc:
      permalink: "#"
  - tables
  